name: ${project.name}
main: net.downwithdestruction.dwdshop.DwDShopPlugin
version: ${project.version}
depends: [Vault]
dev-url: ${project.url}
commands:
    ashop:
      usage: /ashop
      description: All shop-related commands